---
run:
  timeout: "5m"
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/authzed/spicedb"
  rowserrcheck:
    packages:
      - "github.com/jmoiron/sqlx"
      - "github.com/jackc/pgx"
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "deadcode"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gofumpt"
    - "goprintffuncname"
    - "goimports"
    - "gosimple"
    - "govet"
    - "ineffassign"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "structcheck"
    - "typecheck"
    - "unused"
    - "varcheck"
issues:
  exclude-rules:
    - path: "internal/namespace"
      linters:
        - "revive"
    - path: "pkg/namespace"
      linters:
        - "revive"
    - text: "tx.Rollback()"
      linters:
        - "errcheck"
