---
run:
  timeout: "5m"
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/authzed/spicedb"
  rowserrcheck:
    packages:
      - "github.com/jmoiron/sqlx"
      - "github.com/jackc/pgx"
  gosec:
    excludes:
      - "G404" # Allow the usage of math/rand
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "deadcode"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gofumpt"
    - "goimports"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "ifshort"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "structcheck"
    - "stylecheck"
    - "tenv"
    - "typecheck"
    - "unconvert"
    - "unused"
    - "varcheck"
issues:
  exclude-rules:
    - path: "internal/namespace"
      linters:
        - "revive"
    - path: "pkg/namespace"
      linters:
        - "revive"
    - text: "tx.Rollback()"
      linters:
        - "errcheck"
